<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="io.personium.core.model.lock.UnitUserLockManagerTest" time="60.064" tests="3" errors="3" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/local/openjdk-8/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.262-b10"/>
    <property name="animal.sniffer.skip" value="true"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="/tmp/tmprq437xsg/personium-core"/>
    <property name="maven.javadoc.skip" value="true"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="source.skip" value="true"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/tmp/tmprq437xsg/personium-core"/>
    <property name="java.runtime.version" value="1.8.0_262-b10"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/local/openjdk-8/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="license.skip" value="true"/>
    <property name="maven.conf" value="/usr/share/maven/conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="maven.test.failure.ignore" value="true"/>
    <property name="os.version" value="4.15.0-109-generic"/>
    <property name="library.jansi.path" value="/usr/share/maven/lib/jansi-native"/>
    <property name="user.home" value="/home/jdbl"/>
    <property name="user.timezone" value="Etc/UTC"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="jdbl"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.6.0.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/local/openjdk-8/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test -e --fail-never -ntp -Dmaven.test.failure.ignore=true -B -Dmaven.javadoc.skip=true -Drat.skip=true -Danimal.sniffer.skip=true -Dmaven.javadoc.skip=true -Dlicense.skip=true -Dsource.skip=true"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_262"/>
    <property name="java.ext.dirs" value="/usr/local/openjdk-8/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/local/openjdk-8/jre/lib/resources.jar:/usr/local/openjdk-8/jre/lib/rt.jar:/usr/local/openjdk-8/jre/lib/sunrsasign.jar:/usr/local/openjdk-8/jre/lib/jsse.jar:/usr/local/openjdk-8/jre/lib/jce.jar:/usr/local/openjdk-8/jre/lib/charsets.jar:/usr/local/openjdk-8/jre/lib/jfr.jar:/usr/local/openjdk-8/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="rat.skip" value="true"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="ロックされていない場合にFALSEを返すこと" classname="io.personium.core.model.lock.UnitUserLockManagerTest" time="12.047">
    <error message="Server connection error." type="io.personium.core.PersoniumCoreException">io.personium.core.PersoniumCoreException: Server connection error.
</error>
    <system-out><![CDATA[2020-07-30 22:10:00.318 [main] [INFO ] Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 12,016 ms ago } - MemcachedClient
net.spy.memcached.OperationTimeoutException: Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 12,016 ms ago }
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1240)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1256)
	at io.personium.core.utils.MemcachedClient.get(MemcachedClient.java:77)
	at io.personium.core.model.lock.MemcachedLockManager.doGetUnituserLock(MemcachedLockManager.java:77)
	at io.personium.core.model.lock.UnitUserLockManager.hasLockObject(UnitUserLockManager.java:46)
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされていない場合にFALSEを返すこと(UnitUserLockManagerTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:69)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229)
	... 29 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:09:48.294 INFO net.spy.memcached.MemcachedConnection:  Setting retryQueueSize to -1
2020-07-30 22:09:48.295 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2020-07-30 22:09:48.298 INFO net.spy.memcached.MemcachedConnection:  Setting retryQueueSize to -1
2020-07-30 22:09:48.298 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:09:48.298 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2020-07-30 22:09:48.299 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 1.
2020-07-30 22:09:48.305 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:09:48.305 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 1.
2020-07-30 22:09:48.313 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for UnitUserLock-u0_unituserlocktest.
2020-07-30 22:09:52.301 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:09:52.301 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:09:52.301 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 2.
2020-07-30 22:09:52.309 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:09:52.309 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:09:52.309 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 2.
2020-07-30 22:10:00.309 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:00.309 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:00.309 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 3.
2020-07-30 22:10:00.317 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:10:00.317 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:00.318 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 3.
]]></system-err>
  </testcase>
  <testcase name="異なるUnitUserでロックされている場合にFALSEを返すこと" classname="io.personium.core.model.lock.UnitUserLockManagerTest" time="24.016">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException">io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.UnitUserLockManagerTest.異なるUnitUserでロックされている場合にFALSEを返すこと(UnitUserLockManagerTest.java:73)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.UnitUserLockManagerTest.異なるUnitUserでロックされている場合にFALSEを返すこと(UnitUserLockManagerTest.java:73)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at io.personium.core.model.lock.UnitUserLockManagerTest.異なるUnitUserでロックされている場合にFALSEを返すこと(UnitUserLockManagerTest.java:73)
</error>
    <system-out><![CDATA[2020-07-30 22:10:12.333 [main] [INFO ] Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 24,034 ms ago } - MemcachedClient
net.spy.memcached.OperationTimeoutException: Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 24,034 ms ago }
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1240)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1256)
	at io.personium.core.utils.MemcachedClient.get(MemcachedClient.java:77)
	at io.personium.core.model.lock.MemcachedLockManager.doGetUnituserLock(MemcachedLockManager.java:77)
	at io.personium.core.model.lock.UnitUserLockManager.registLockObjct(UnitUserLockManager.java:66)
	at io.personium.core.model.lock.UnitUserLockManagerTest.異なるUnitUserでロックされている場合にFALSEを返すこと(UnitUserLockManagerTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:69)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229)
	... 29 common frames omitted
2020-07-30 22:10:12.333 [main] [ERROR] Failed to connect memcached. - MemcachedClient
2020-07-30 22:10:24.335 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.delete(MemcachedClient.java:171)
	at io.personium.core.model.lock.MemcachedLockManager.doReleaseLock(MemcachedLockManager.java:37)
	at io.personium.core.model.lock.UnitUserLockManager.releaseLockObject(UnitUserLockManager.java:94)
	at io.personium.core.model.lock.UnitUserLockManagerTest.異なるUnitUserでロックされている場合にFALSEを返すこと(UnitUserLockManagerTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:10:00.332 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for UnitUserLock-u0_unituserlocktestXX.
2020-07-30 22:10:06.211 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:06.212 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:06.212 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:07.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:07.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:07.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:07.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:07.794 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:07.794 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:10.585 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:10.585 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:10.586 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:10.594 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:10.595 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:10.595 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:12.334 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for UnitUserLock-u0_unituserlocktestXX.
2020-07-30 22:10:13.685 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:13.685 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:13.685 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:13.693 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:13.693 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:13.693 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:16.312 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:16.313 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:16.313 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 4.
2020-07-30 22:10:16.321 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=3, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:10:16.322 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=3, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:16.323 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=3, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 4.
]]></system-err>
  </testcase>
  <testcase name="ロックされている場合にTRUEを返すこと" classname="io.personium.core.model.lock.UnitUserLockManagerTest" time="23.999">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException">io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされている場合にTRUEを返すこと(UnitUserLockManagerTest.java:48)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされている場合にTRUEを返すこと(UnitUserLockManagerTest.java:48)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされている場合にTRUEを返すこと(UnitUserLockManagerTest.java:48)
</error>
    <system-out><![CDATA[2020-07-30 22:10:36.338 [main] [INFO ] Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 48,039 ms ago } - MemcachedClient
net.spy.memcached.OperationTimeoutException: Timeout waiting for value: waited 12,000 ms. Node status: Connection Status { localhost/127.0.0.1:11211 active: false, authed: true, last read: 48,039 ms ago }
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1240)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1256)
	at io.personium.core.utils.MemcachedClient.get(MemcachedClient.java:77)
	at io.personium.core.model.lock.MemcachedLockManager.doGetUnituserLock(MemcachedLockManager.java:77)
	at io.personium.core.model.lock.UnitUserLockManager.registLockObjct(UnitUserLockManager.java:66)
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされている場合にTRUEを返すこと(UnitUserLockManagerTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.internal.GetFuture.get(GetFuture.java:69)
	at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229)
	... 29 common frames omitted
2020-07-30 22:10:36.338 [main] [INFO ] Failed to connect memcached. - MemcachedClient
2020-07-30 22:10:48.339 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.delete(MemcachedClient.java:171)
	at io.personium.core.model.lock.MemcachedLockManager.doReleaseLock(MemcachedLockManager.java:37)
	at io.personium.core.model.lock.UnitUserLockManager.releaseLockObject(UnitUserLockManager.java:94)
	at io.personium.core.model.lock.UnitUserLockManagerTest.ロックされている場合にTRUEを返すこと(UnitUserLockManagerTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: localhost/127.0.0.1:11211
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:10:24.337 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for UnitUserLock-u0_unituserlocktest.
2020-07-30 22:10:36.241 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:36.241 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:36.241 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:36.338 WARN net.spy.memcached.MemcachedConnection:  Could not redistribute to another node, retrying primary node for UnitUserLock-u0_unituserlocktest.
2020-07-30 22:10:37.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:37.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:37.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:37.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:37.822 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:37.822 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:40.613 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:40.613 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:40.613 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:40.626 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:40.626 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:40.626 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:43.713 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:43.714 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:43.714 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:43.721 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:43.721 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:43.722 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:10:46.333 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=5, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:10:46.333 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=5, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:46.334 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=5, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 5.
2020-07-30 22:10:46.341 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:10:46.341 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:10:46.345 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 5.
]]></system-err>
  </testcase>
</testsuite>