<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="io.personium.core.model.lock.CellLockManagerTest" time="191.945" tests="16" errors="16" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/local/openjdk-8/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.262-b10"/>
    <property name="animal.sniffer.skip" value="true"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="/tmp/tmprq437xsg/personium-core"/>
    <property name="maven.javadoc.skip" value="true"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="source.skip" value="true"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/tmp/tmprq437xsg/personium-core"/>
    <property name="java.runtime.version" value="1.8.0_262-b10"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/local/openjdk-8/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="license.skip" value="true"/>
    <property name="maven.conf" value="/usr/share/maven/conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="maven.test.failure.ignore" value="true"/>
    <property name="os.version" value="4.15.0-109-generic"/>
    <property name="library.jansi.path" value="/usr/share/maven/lib/jansi-native"/>
    <property name="user.home" value="/home/jdbl"/>
    <property name="user.timezone" value="Etc/UTC"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="jdbl"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.6.0.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/local/openjdk-8/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test -e --fail-never -ntp -Dmaven.test.failure.ignore=true -B -Dmaven.javadoc.skip=true -Drat.skip=true -Danimal.sniffer.skip=true -Dmaven.javadoc.skip=true -Dlicense.skip=true -Dsource.skip=true"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_262"/>
    <property name="java.ext.dirs" value="/usr/local/openjdk-8/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/local/openjdk-8/jre/lib/resources.jar:/usr/local/openjdk-8/jre/lib/rt.jar:/usr/local/openjdk-8/jre/lib/sunrsasign.jar:/usr/local/openjdk-8/jre/lib/jsse.jar:/usr/local/openjdk-8/jre/lib/jce.jar:/usr/local/openjdk-8/jre/lib/charsets.jar:/usr/local/openjdk-8/jre/lib/jfr.jar:/usr/local/openjdk-8/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="rat.skip" value="true"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="参照カウントをインクリメント後デクリメントするとクリアされる" classname="io.personium.core.model.lock.CellLockManagerTest" time="23.919">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:11:00.348 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:11:12.349 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:11:06.269 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:06.269 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:06.269 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:07.849 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:07.850 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:07.850 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:07.850 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:07.851 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:07.851 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:10.644 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:10.644 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:10.645 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:10.655 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:10.656 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:10.656 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
]]></system-err>
  </testcase>
  <testcase name="参照カウントをインクリメント後デクリメントするとクリアされる" classname="io.personium.core.model.lock.CellLockManagerTest" time="23.919">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="セルの処理状態を一括削除処理中に設定する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.006">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:11:24.353 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:11:36.354 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:11:13.741 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:13.741 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:13.741 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:13.750 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:13.750 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:13.751 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:16.337 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=8, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:11:16.337 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=8, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:16.337 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=8, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:11:16.373 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:16.373 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:16.373 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 6.
2020-07-30 22:11:36.297 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:36.297 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:36.298 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
]]></system-err>
  </testcase>
  <testcase name="セルの処理状態を一括削除処理中に設定する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.006">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="初期化後の参照カウントをインクリメントすると2になる" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.003">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:11:48.356 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:12:00.357 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:11:37.877 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:37.877 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:37.877 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:37.881 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:37.881 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:37.881 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:40.673 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:40.673 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:40.673 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:40.685 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:40.685 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:40.685 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:43.769 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:43.769 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:43.769 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:43.781 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:43.781 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:43.781 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:11:46.345 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=10, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:11:46.345 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=10, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:46.346 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=10, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 7.
2020-07-30 22:11:46.401 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:11:46.401 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:11:46.401 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 7.
]]></system-err>
  </testcase>
  <testcase name="初期化後の参照カウントをインクリメントすると2になる" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.003">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="セルの処理状態を一括削除してない中に設定する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.008">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:12:12.365 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:12:24.366 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:12:06.325 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:06.325 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:06.325 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:07.905 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:07.905 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:07.905 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:07.909 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:07.909 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:07.909 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:10.703 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:10.703 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:10.703 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:10.713 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:10.713 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:10.714 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:13.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:13.793 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:13.794 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:13.809 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:13.809 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:13.810 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:16.349 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=13, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:12:16.349 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=13, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:16.350 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=13, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 8.
2020-07-30 22:12:16.429 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:16.429 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:16.429 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 8.
]]></system-err>
  </testcase>
  <testcase name="セルの処理状態を一括削除してない中に設定する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.008">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="Cell参照カウントが存在しない場合" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:12:36.367 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:12:48.368 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:12:36.353 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:36.353 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:36.353 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:37.933 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:37.933 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:37.933 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:37.937 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:37.937 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:37.937 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:40.733 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:40.733 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:40.733 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:40.743 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:40.743 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:40.744 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:43.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:43.821 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:43.821 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:43.837 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:43.837 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:43.837 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:12:46.359 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=15, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:12:46.360 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=15, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:46.360 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=15, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 9.
2020-07-30 22:12:46.457 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:12:46.457 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:12:46.457 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 9.
]]></system-err>
  </testcase>
  <testcase name="Cell参照カウントが存在しない場合" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="セルの処理状態が一括削除してない中の場合に状態を一括削除処理中に更新する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.003">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:13:00.371 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:13:12.371 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:13:06.381 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:06.381 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:06.381 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:07.961 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:07.962 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:07.962 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:07.965 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:07.965 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:07.966 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:10.761 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:10.761 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:10.761 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:10.773 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:10.773 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:10.773 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
]]></system-err>
  </testcase>
  <testcase name="セルの処理状態が一括削除してない中の場合に状態を一括削除処理中に更新する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.003">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="Cell参照カウントを初期値1で新規作成する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:13:24.373 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:13:36.374 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:13:13.849 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:13.849 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:13.849 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:13.865 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:13.865 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:13.865 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:16.362 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=18, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:13:16.362 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=18, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:16.362 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=18, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 10.
2020-07-30 22:13:16.485 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:16.485 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:16.485 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 10.
]]></system-err>
  </testcase>
  <testcase name="Cell参照カウントを初期値1で新規作成する" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
  <testcase name="参照カウントが存在しない状態でデクリメントすると0が返却される" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
]]></error>
    <system-out><![CDATA[2020-07-30 22:13:48.375 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.before(CellLockManagerTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 29 common frames omitted
2020-07-30 22:14:00.376 [main] [INFO ] Timed out waiting for operation - MemcachedClient
java.lang.RuntimeException: Timed out waiting for operation
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
	at io.personium.core.utils.MemcachedClient.clear(MemcachedClient.java:153)
	at io.personium.core.model.lock.MemcachedLockManager.doDeleteAllLocks(MemcachedLockManager.java:42)
	at io.personium.core.model.lock.LockManager.deleteAllLocks(LockManager.java:148)
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:167)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2401)
	at net.spy.memcached.MemcachedClient$15.get(MemcachedClient.java:2378)
	at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:140)
	... 28 common frames omitted
]]></system-out>
    <system-err><![CDATA[2020-07-30 22:13:36.409 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:36.409 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:36.409 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:37.992 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:37.993 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:37.993 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:37.993 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:37.993 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:37.993 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:40.790 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:40.791 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:40.791 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:40.799 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:40.800 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:40.839 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:43.878 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:43.878 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:43.879 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:43.894 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:43.895 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:43.895 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 12.
2020-07-30 22:13:46.370 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=20, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
2020-07-30 22:13:46.370 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=20, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:46.371 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=20, #iq=0, topRop=null, topWop=Cmd: get Keys: UnitUserLock-u0_unituserlocktestExp: 0, toWrite=0, interested=0}, attempt 11.
2020-07-30 22:13:46.512 INFO net.spy.memcached.MemcachedConnection:  Reconnecting {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2020-07-30 22:13:46.512 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to failure to connect to {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:691)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)
2020-07-30 22:13:46.513 WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=localhost/127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}, attempt 11.
]]></system-err>
  </testcase>
  <testcase name="参照カウントが存在しない状態でデクリメントすると0が返却される" classname="io.personium.core.model.lock.CellLockManagerTest" time="24.002">
    <error message="java.lang.RuntimeException: Timed out waiting for operation" type="io.personium.core.utils.MemcachedClient$MemcachedClientException"><![CDATA[io.personium.core.utils.MemcachedClient$MemcachedClientException: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: java.lang.RuntimeException: Timed out waiting for operation
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
Caused by: net.spy.memcached.internal.CheckedOperationTimeoutException: Timed out waiting for operation - failing node: <unknown>
	at io.personium.core.model.lock.CellLockManagerTest.after(CellLockManagerTest.java:49)
]]></error>
  </testcase>
</testsuite>